### ISSUE TITLE
Bug with "Unbloat cmd/vitotrol/main.go by introducing actions"

### ISSUE THREAD

**Issue by maitrey0da** [maxatome/go-vitotrol#1]
Hi,

I'm using your amazing tool in order to push temperature into my influxdb/grafana stack. But, in your last release, I can't run actions.go 
`
/usr/local/go/bin/go run /home/maitrey0da/dev/go-workdir/actions.go -login foo -password bar rget IndoorTemp OutdoorTemp
command-line-arguments
./actions.go:36: undefined: Options
./actions.go:52: undefined: Options
`

Can you help me or review the readme ?

Thanks

**Comment by maxatome** [comment]
Hi,
That's because you build only one go file (actions.go) instead of both (actions.go + main.go).
I just updated the README file. I hope it is clearer now.
Regards.
