### ISSUE TITLE
Cannot fetch data anymore

### ISSUE THREAD

**Issue by dmpolukhin** [maxatome/go-vitotrol#11]
Two days ago go-vitotrol stopped working for me. It just hangs on any get command like ` vitotrol -debug -verbose get BoilerTemp`. In web interface and the App everything is fine so it seems like some issue with data access via APIs.

Any ideas how to fix it?

**Comment by maxatome** [comment]
Hi,
Is your `vitotrol` app compiled with last version of sources?
What does `vitotrol -debug -verbose get BoilerTemp` display?

**Comment by dmpolukhin** [comment]
It seems to be some network issue on my side. So connection to API endpoint hung with no response.
