### ISSUE TITLE
can't set konf_neigung to non-integer value 

### ISSUE THREAD

**Issue by monojk** [maxatome/go-vitotrol#15]
I try to set the konf_neigung_rw-0x0b35 to 1.3 but it finally rounds the value (seen by rget)  although it prints that the wanted value was successfully set. At the Vitodens-300W I see 1,0 instead of 1,3 
```
pi@rp4b:~ $ /home/pi/go/bin/vitotrol -verbose set konf_neigung_rw-0x0b35 1.3
Working with device VT 200 (HO1C)@75014............
konf_neigung_rw-0x0b35 attribute successfully set to `1.3'
pi@rp4b:~ $ /home/pi/go/bin/vitotrol rget konf_neigung_rw-0x0b35
konf_neigung_rw-0x0b35: 1@2022-10-19 11:21:28 (konf_neigung_rw)

pi@rp4b:~ $ /home/pi/go/bin/vitotrol -verbose set konf_neigung_rw-0x0b35 2
Working with device VT 200 (HO1C)@75014............
konf_neigung_rw-0x0b35 attribute successfully set to `2'
pi@rp4b:~ $ /home/pi/go/bin/vitotrol rget konf_neigung_rw-0x0b35
konf_neigung_rw-0x0b35: 2@2022-10-19 11:22:20 (konf_neigung_rw)

pi@rp4b:~ $ /home/pi/go/bin/vitotrol -verbose set konf_neigung_rw-0x0b35 1
Working with device VT 200 (HO1C)@75014............
konf_neigung_rw-0x0b35 attribute successfully set to `1'
pi@rp4b:~ $ /home/pi/go/bin/vitotrol rget konf_neigung_rw-0x0b35
konf_neigung_rw-0x0b35: 1@2022-10-19 11:23:03 (konf_neigung_rw)

```

**Comment by monojk** [comment]
Any progress here?

**Comment by maxatome** [comment]
Nope.
It probably means this attribute accepts only integer values?
Do you succeed to set it to a floating value using another way (vitodata app or website)? If yes, print the value using vitotrol to see it. Perhaps the decimal separator should not be a "."?

**Comment by maxatome** [comment]
And when you set it to 1.4 using the web interface vitodata100, what does `/home/pi/go/bin/vitotrol rget konf_neigung_rw-0x0b35` print?

**Comment by monojk** [comment]
I set 1,4 on the web interface and get the expected value:
```
/home/pi/go/bin/vitotrol rget konf_neigung_rw-0x0b35
konf_neigung_rw-0x0b35: 1.4@2024-09-18 15:42:55 (konf_neigung_rw)
```

**Comment by maxatome** [comment]
At https://github.com/maxatome/go-vitotrol/blob/master/vitotrol.go#L39, you can try to add:
```diff
 	client := &http.Client{}
+ 	log.Println("SEND(" + reqBody + ")")
 	req, err := http.NewRequest("POST", MainURL,
```
to check you have well:
```xml
SEND(<DatapointId>…</DatapointId><Wert>1.4</Wert>)
```
after recompiling when you do:
```
vitotrol -verbose set konf_neigung_rw-0x0b35 1.4
```

**Comment by monojk** [comment]
Ok, can you refresh my mind how to Compiler the changes?

**Comment by maxatome** [comment]
1. retrieve the repo
2. go to vitotrol command directory
3. build vitotrol executable

↓
```
git clone https://github.com/maxatome/go-vitotrol.git
cd go-vitotrol/cmd/vitotrol
go install .
```

**Comment by monojk** [comment]
Yes, I saw
```
<DatapointId>2869</DatapointId><Wert>1.4</Wert>
```

**Comment by maxatome** [comment]
In this case I don't know what to do to fix this issue, as if 1.4 is well sent then I don't understand why the server only keeps the integer part :(

**Comment by maxatome** [comment]
we can try `1,4` instead of `1.4` as a last resort:
here https://github.com/maxatome/go-vitotrol/blob/master/vitotrol.go#L10 add
```diff
 	"sort"
+	"strings"
 )
```
then just before the `log.Println("SEND(" + reqBody + ")")` line you added above:
```
 	client := &http.Client{}
+ 	reqBody = strings.Replace(reqBody, ".", ",", 1)
+	log.Println("SEND(" + reqBody + ")")
 	req, err := http.NewRequest("POST", MainURL,
```

**Comment by monojk** [comment]
I am debugging further with setting also on the vitotrol100 web interface. Therse seems to be some delay. A mouse over the field says that there is only a gradual and delayed change. Maybe that is reason why the change isn't reflected by the rget call...

**Comment by monojk** [comment]
Great, this fixed the problem:
```
        "strings"
....
 	reqBody = strings.Replace(reqBody, ".", ",", 1)
```
Many thanks, merci beaucoup.

**Comment by maxatome** [comment]
Cool! We are lucky :D
I will do a PR ASAP.

**Comment by maxatome** [comment]
@monojk could you please test the PR #16?
In the go-vitotrol directory, do:
```
git checkout -- .
git fetch
git checkout fix-float
cd cmd/vitotrol
go install .

**Comment by monojk** [comment]
Thanks, it works:
```
$ /home/pi/go/bin/vitotrol -verbose set konf_neigung_rw-0x0b35 1.4
Working with device VT 200 (HO1C)@7501..............
konf_neigung_rw-0x0b35 attribute successfully set to `1,4'

$/home/pi/go/bin/vitotrol rget konf_neigung_rw-0x0b35
konf_neigung_rw-0x0b35: 1.4@2024-09-19 09:50:28 (konf_neigung_rw)
```

**Comment by maxatome** [comment]
Cool!
