### ISSUE TITLE
Influxdb database

### ISSUE THREAD

**Issue by maitrey0da** [maxatome/go-vitotrol#2]
Hi,

I wrote a (bash) glue to push go-vitotrol data in a influxDB database. InfluxDB share a [golang client](https://github.com/influxdata/influxdb/tree/master/client) to [write data](https://docs.influxdata.com/influxdb/v1.2/guides/writing_data/).

I would like to know if this feature could be integrate go-vitotrol.

Thanks

**Comment by maxatome** [comment]
Hello,
Perhaps is it better to create a special repository for that?
If this glue was done using golang, I could add it to an example directory, but as it is bash scripting, I do not think it is the best place to host it.
That's said, I would be happy to reference your repository when created...
Regards.

**Comment by maxatome** [comment]
Hi @maitrey0da, have a look at https://github.com/maxatome/vitotrol2influx

As I will close this issue, please open one in [vitotrol2influx](https://github.com/maxatome/vitotrol2influx
) if something is missing regarding your needs.

Best regards.
