### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by joeblew99** [maxatome/go-vitotrol#3]
I am about to buy a boiler from this company.
Did you try talking to the controller they sale so you don't have to use their web service ?

**Comment by maxatome** [comment]
It seems that the "controller" (vitocom 100 LAN1) runs an HTTP server, but I do not know any API running on it... :(

**Comment by joeblew99** [comment]
ok. 
Mhh. i think i might have to use bacnet then and go direct.
I want direct control because i need to control fans, dampers, fan coils, heat pumps
