### ISSUE TITLE
No devices

### ISSUE THREAD

**Issue by ldb2000** [maxatome/go-vitotrol#5]
Hi,
When I run the following command, I have a "no devices" response.

Executing the --debug show me that the Name can be retreived but no devices. What I have done wrong ?

Thanks

`$  ./vitotrol --debug devices`

2018/08/23 11:41:25 <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><LoginResponse xmlns="http://www.e-controlnet.de/services/vii/"><LoginResult><Ergebnis>0</Ergebnis><ErgebnisText>Kein Fehler</ErgebnisText><TechVersion>2.5.7.0</TechVersion><Anrede>1</Anrede><Vorname>Myname</Vorname><Nachname>Myname</Nachname></LoginResult></LoginResponse></soap:Body></soap:Envelope>
2018/08/23 11:41:26 <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><GetDevicesResponse xmlns="http://www.e-controlnet.de/services/vii/"><GetDevicesResult><Ergebnis>0</Ergebnis><ErgebnisText>Kein Fehler</ErgebnisText><AnlageListe /></GetDevicesResult></GetDevicesResponse></soap:Body></soap:Envelope>

**Comment by maxatome** [comment]
You can try to test using the [Viessmann vitodata100](https://vitodata100.viessmann.com/VD100/VD100/Login/Login.aspx) service.
Once logged in, you should be able to see your "Installation" then the devices inside it.
If you see your "Installation" and any device inside it, I do not know what happens as I request devices using the most simple way described [here](https://www.viessmann.com/app_vitodata/VIIWebService-1.16.0.0/iPhoneWebService.asmx?op=GetDevices).

**Comment by ldb2000** [comment]
Hi maxatome,

I have a vitoconnect that should explain why it is not working. 
Sounds that the only way to retrieve information is by using the web service 
https://api.viessmann.io/vitotrol/soap/v1.0/iPhoneWebService.asm and not the vitodata one.

**Comment by maxatome** [comment]
Hi,
Hmm... Bad news, seems to be a new API...
Your link gives me a blank page.

**Comment by monojk** [comment]
Is this code no longer functional due to changes in Viesmann's interface?
